# Generated by Django 5.2.7 on 2025-10-18 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list, help_text='List of generated questions')),
                ('answers', models.JSONField(default=list, help_text='List of user answers')),
                ('report', models.JSONField(default=dict, help_text='AI analysis report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.demo')),
            ],
        ),
    ]
