# Generated by Django 4.2.7 on 2025-10-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_question_number',
            field=models.IntegerField(default=0, help_text='Current question index'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted resume text'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(blank=True, help_text='Target job role', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='service_state',
            field=models.JSONField(default=dict, help_text='InterviewLLMService state'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=5, help_text='Total number of questions'),
        ),
    ]
