# Generated by Django 4.2.7 on 2025-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interviewsession_current_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='behavioral_report',
            field=models.JSONField(default=dict, help_text='Behavioral interview report (first 5 questions)'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='dsa_pseudocode',
            field=models.TextField(blank=True, help_text="User's pseudocode submission"),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='dsa_question',
            field=models.JSONField(default=dict, help_text='DSA question from ask_ques_get_ans'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='dsa_report',
            field=models.JSONField(default=dict, help_text='DSA interview report'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='dsa_session_idx',
            field=models.IntegerField(default=-1, help_text='Index in ANALYSIS_LOG'),
        ),
    ]
