# Generated by Django 5.2.7 on 2025-10-19 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_interviewsession_behavioral_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(default='Anonymous Candidate', max_length=200)),
                ('candidate_email', models.EmailField(default='candidate@example.com', max_length=254)),
                ('position', models.CharField(default='Software Engineer', max_length=200)),
                ('overall_score', models.IntegerField(default=0, help_text='Overall interview score (0-100)')),
                ('overall_rating', models.CharField(default='Average', help_text='Excellent/Good/Average/Below Average', max_length=50)),
                ('strengths', models.JSONField(default=list, help_text='List of candidate strengths')),
                ('areas_for_improvement', models.JSONField(default=list, help_text='List of areas for improvement')),
                ('report_data', models.JSONField(default=dict, help_text='Complete interview report data')),
                ('interview_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.interviewsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
