# Generated by Django 5.2.7 on 2025-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreport',
            name='decision',
            field=models.CharField(default='Pending', help_text='Pending/Accepted/Declined', max_length=20),
        ),
    ]
