# Generated by Django 5.2.7 on 2025-12-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interviewreport_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='interviewreport',
            name='session',
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='behavioral_report',
            field=models.JSONField(default=dict, help_text='Behavioral interview report (first 5 questions)'),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='conversation',
            field=models.JSONField(default=list, help_text='Complete interview conversation (questions and answers)'),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='dsa_pseudocode',
            field=models.TextField(blank=True, help_text="User's pseudocode submission"),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='dsa_question',
            field=models.JSONField(default=dict, help_text='DSA question from ask_ques_get_ans'),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='dsa_report',
            field=models.JSONField(default=dict, help_text='DSA interview report'),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='dsa_session_idx',
            field=models.IntegerField(default=-1, help_text='Index in ANALYSIS_LOG'),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted resume text'),
        ),
        migrations.AlterField(
            model_name='interviewreport',
            name='candidate_email',
            field=models.EmailField(default='ashkalbhattaarkar@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='interviewreport',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.jobdescription'),
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
    ]
