"""
Django management command to populate the database with sample job descriptions.

This command creates default job descriptions that can be used for interview sessions.
It uses get_or_create to avoid duplicates and provides options to clear existing data.
"""

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from api.models import JobDescription


class Command(BaseCommand):
    """Management command to populate job descriptions."""
    
    help = 'Populate the database with sample job descriptions for interview sessions'

    def add_arguments(self, parser):
        """Add command-line arguments."""
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear all existing job descriptions before populating',
        )
        parser.add_argument(
            '--verbose',
            action='store_true',
            help='Enable verbose output',
        )

    def _validate_job_data(self, job_data):
        """
        Validate job description data against model constraints.
        
        Args:
            job_data (dict): Dictionary containing job description data
            
        Returns:
            tuple: (is_valid, error_message)
        """
        # Validate title
        if 'title' not in job_data or not job_data['title']:
            return False, "Title is required"
        
        if len(job_data['title']) > 200:
            return False, f"Title exceeds maximum length of 200 characters (got {len(job_data['title'])})"
        
        # Validate description
        if 'description' not in job_data:
            return False, "Description is required"
        
        return True, None

    def _get_job_descriptions_data(self):
        """
        Return a list of job description data dictionaries.
        
        Each dictionary must contain:
        - title (str): Job title, max 200 characters (CharField)
        - description (str): Job description text (TextField)
        
        Note: 'id' and 'created_at' are auto-generated by the model.
        
        Returns:
            list: List of dictionaries with 'title' and 'description' keys
        """
        return [
            {
                'title': 'Software Engineering Jobs',
                'description': '''We are seeking a talented Software Engineer to join our dynamic engineering team. 
The ideal candidate will have strong programming skills in languages such as Python, Java, or JavaScript, 
experience with software development best practices, and a passion for building scalable, high-quality applications.

Key Responsibilities:
- Design, develop, and maintain robust software applications
- Collaborate with cross-functional teams to define and implement new features
- Write clean, maintainable, and well-documented code
- Participate in code reviews and contribute to technical discussions
- Debug and resolve complex technical issues
- Stay current with emerging technologies and industry trends

Required Skills:
- Bachelor's degree in Computer Science or related field
- Proficiency in at least one programming language (Python, Java, JavaScript, etc.)
- Experience with version control systems (Git)
- Strong problem-solving and analytical skills
- Understanding of data structures and algorithms
- Experience with software development lifecycle and agile methodologies

Preferred Qualifications:
- Experience with cloud platforms (AWS, Azure, GCP)
- Knowledge of database systems (SQL and NoSQL)
- Familiarity with microservices architecture
- Experience with CI/CD pipelines
- Contributions to open-source projects'''
            },
            {
                'title': 'Product Manager Jobs',
                'description': '''We are looking for an experienced Product Manager to drive product strategy and 
execution for our innovative platform. The successful candidate will work closely with engineering, design, 
and business teams to deliver products that meet customer needs and business objectives.

Key Responsibilities:
- Define product vision, strategy, and roadmap
- Gather and prioritize product requirements from stakeholders
- Work closely with engineering teams to deliver features on time
- Conduct market research and competitive analysis
- Define and track key product metrics and KPIs
- Collaborate with design teams to create user-centric solutions
- Communicate product plans and progress to executive leadership

Required Skills:
- Bachelor's degree in Business, Engineering, or related field
- 3+ years of product management experience
- Strong analytical and problem-solving skills
- Excellent communication and presentation abilities
- Experience with agile development methodologies
- Ability to work effectively with cross-functional teams
- Customer-focused mindset with strong user empathy

Preferred Qualifications:
- MBA or advanced degree
- Technical background or experience working with engineering teams
- Experience with product analytics tools
- Knowledge of UX/UI design principles
- Experience in B2B or SaaS products'''
            },
            {
                'title': 'Data Science Jobs',
                'description': '''Join our data science team to extract insights from complex datasets and build 
predictive models that drive business decisions. We are seeking a Data Scientist with strong analytical skills 
and experience in machine learning and statistical analysis.

Key Responsibilities:
- Analyze large datasets to identify trends, patterns, and insights
- Develop and deploy machine learning models for prediction and classification
- Collaborate with business stakeholders to understand requirements
- Create data visualizations and reports to communicate findings
- Clean, preprocess, and validate data for analysis
- Stay current with latest data science techniques and tools
- Present findings and recommendations to technical and non-technical audiences

Required Skills:
- Master's degree in Data Science, Statistics, Computer Science, or related field
- Strong programming skills in Python or R
- Experience with machine learning frameworks (scikit-learn, TensorFlow, PyTorch)
- Proficiency in SQL and database querying
- Strong statistical analysis and mathematical skills
- Experience with data visualization tools (Tableau, Power BI, matplotlib)
- Excellent problem-solving and critical thinking abilities

Preferred Qualifications:
- PhD in a quantitative field
- Experience with big data technologies (Spark, Hadoop)
- Knowledge of deep learning and neural networks
- Experience with cloud platforms (AWS, Azure, GCP)
- Published research papers or contributions to data science community
- Experience with A/B testing and experimentation'''
            },
            {
                'title': 'UX Designer Interview',
                'description': '''We are seeking a creative and user-focused UX Designer to join our design team. 
The ideal candidate will have a strong portfolio demonstrating user-centered design thinking and experience 
creating intuitive, accessible digital experiences.

Key Responsibilities:
- Conduct user research and usability testing to understand user needs
- Create user personas, journey maps, and wireframes
- Design user interfaces for web and mobile applications
- Collaborate with product managers and engineers throughout the design process
- Create interactive prototypes to validate design concepts
- Maintain and evolve design systems and style guides
- Present design concepts and rationale to stakeholders

Required Skills:
- Bachelor's degree in Design, Human-Computer Interaction, or related field
- Strong portfolio showcasing UX/UI design work
- Proficiency in design tools (Figma, Sketch, Adobe XD)
- Understanding of user-centered design principles
- Experience with user research methods
- Strong visual design skills and attention to detail
- Excellent communication and collaboration skills

Preferred Qualifications:
- Experience with prototyping tools (Framer, Principle, InVision)
- Knowledge of front-end development (HTML, CSS, JavaScript)
- Experience with accessibility standards (WCAG)
- Understanding of information architecture
- Experience designing for multiple platforms (web, mobile, tablet)
- Background in psychology or behavioral science'''
            },
            {
                'title': 'DevOps Engineer Interview',
                'description': '''We are looking for a skilled DevOps Engineer to help build and maintain our 
cloud infrastructure and CI/CD pipelines. The ideal candidate will have experience with automation, 
containerization, and cloud platforms.

Key Responsibilities:
- Design, implement, and maintain cloud infrastructure (AWS, Azure, GCP)
- Build and maintain CI/CD pipelines for automated deployments
- Implement infrastructure as code using tools like Terraform or CloudFormation
- Monitor system performance and troubleshoot infrastructure issues
- Ensure system security and compliance with best practices
- Automate operational processes and reduce manual intervention
- Collaborate with development teams to improve deployment processes

Required Skills:
- Bachelor's degree in Computer Science, Engineering, or related field
- Experience with cloud platforms (AWS, Azure, or GCP)
- Proficiency in containerization technologies (Docker, Kubernetes)
- Experience with CI/CD tools (Jenkins, GitLab CI, GitHub Actions)
- Strong scripting skills (Bash, Python, or similar)
- Knowledge of infrastructure as code (Terraform, Ansible, Chef, Puppet)
- Understanding of networking, security, and system administration

Preferred Qualifications:
- Cloud certifications (AWS Certified Solutions Architect, etc.)
- Experience with monitoring and logging tools (Prometheus, Grafana, ELK)
- Knowledge of microservices architecture
- Experience with service mesh technologies (Istio, Linkerd)
- Understanding of GitOps practices
- Experience with database administration and optimization'''
            }
        ]

    def _clear_existing_jobs(self):
        """Clear all existing job descriptions from the database."""
        count = JobDescription.objects.count()
        if count > 0:
            JobDescription.objects.all().delete()
            self.stdout.write(
                self.style.WARNING(f'Cleared {count} existing job description(s)')
            )
            return count
        return 0

    @transaction.atomic
    def handle(self, *args, **options):
        """
        Execute the command to populate job descriptions.
        
        Args:
            *args: Variable length argument list
            **options: Arbitrary keyword arguments (--clear, --verbose)
        """
        verbose = options.get('verbose', False)
        clear = options.get('clear', False)

        if verbose:
            self.stdout.write('Starting job description population...')

        # Clear existing jobs if requested
        if clear:
            cleared_count = self._clear_existing_jobs()
            if verbose:
                self.stdout.write(f'Cleared {cleared_count} job description(s)')

        # Get job descriptions data
        job_descriptions_data = self._get_job_descriptions_data()
        
        if verbose:
            self.stdout.write(f'Processing {len(job_descriptions_data)} job description(s)...')

        # Track statistics
        created_count = 0
        existing_count = 0
        errors = []

        # Create or update job descriptions
        for job_data in job_descriptions_data:
            try:
                # Validate data against model constraints
                is_valid, validation_error = self._validate_job_data(job_data)
                if not is_valid:
                    error_msg = f'✗ Validation error for "{job_data.get("title", "Unknown")}": {validation_error}'
                    errors.append(error_msg)
                    self.stdout.write(self.style.ERROR(error_msg))
                    continue
                
                # Create or get existing job description
                # Using title as the unique identifier (as per model structure)
                job, created = JobDescription.objects.get_or_create(
                    title=job_data['title'],
                    defaults={
                        'description': job_data['description']
                        # Note: 'id' is AutoField (auto-generated)
                        # Note: 'created_at' is auto_now_add=True (auto-generated)
                    }
                )
                
                if created:
                    created_count += 1
                    message = f'✓ Created job description: {job.title}'
                    self.stdout.write(self.style.SUCCESS(message))
                    if verbose:
                        self.stdout.write(f'   ID: {job.id}, Created: {job.created_at}')
                else:
                    existing_count += 1
                    # Update description if it has changed
                    if job.description != job_data['description']:
                        job.description = job_data['description']
                        job.save(update_fields=['description'])
                        message = f'↻ Updated job description: {job.title}'
                        self.stdout.write(self.style.WARNING(message))
                        if verbose:
                            self.stdout.write(f'   ID: {job.id}, Created: {job.created_at}')
                    else:
                        message = f'○ Job description already exists: {job.title}'
                        if verbose:
                            self.stdout.write(self.style.WARNING(message))
                            self.stdout.write(f'   ID: {job.id}, Created: {job.created_at}')
                        
            except Exception as e:
                error_msg = f'✗ Error processing "{job_data.get("title", "Unknown")}": {str(e)}'
                errors.append(error_msg)
                self.stdout.write(self.style.ERROR(error_msg))

        # Summary
        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS('=' * 50))
        self.stdout.write(self.style.SUCCESS('Population Summary:'))
        self.stdout.write(self.style.SUCCESS(f'  Created: {created_count}'))
        self.stdout.write(self.style.SUCCESS(f'  Existing: {existing_count}'))
        if errors:
            self.stdout.write(self.style.ERROR(f'  Errors: {len(errors)}'))
        self.stdout.write(self.style.SUCCESS('=' * 50))

        if errors:
            raise CommandError(f'Completed with {len(errors)} error(s). Check output above for details.')
        
        self.stdout.write(
            self.style.SUCCESS(f'\n✓ Successfully populated {len(job_descriptions_data)} job description(s)!')
        )
